/**
 * Prepare SDK package for Documents deployment.
 *
 * Runs as part of `npm run build:sdk` after TypeScript compilation.
 * Replaces only `dist/index.js` with the bridge stub. All other compiled
 * modules stay in `dist/` so internal imports like
 * `@realmengine/sdk/dist/vault/VaultChest.js` keep working.
 */

import { existsSync, readFileSync, writeFileSync } from 'fs';
import { dirname, join, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const SDK_DIST = join(ROOT, 'packages', 'sdk', 'dist');
const SDK_TYPES = join(SDK_DIST, 'types');
const SDK_PKG = join(ROOT, 'packages', 'sdk', 'package.json');
const INDEX_SRC = join(SDK_DIST, 'index.js');

const EXPORT_NAMES = [
  'chat', 'party', 'trade', 'events', 'inventory', 'guild', 'GuildRank',
  'INVENTORY_MAIN_SLOT_COUNT', 'INVENTORY_BACKPACK_SLOT_COUNT', 'INVENTORY_TOTAL_SLOT_COUNT',
  'loot', 'discord', 'DiscordWebhook',
  'Self', 'Walking', 'Combat', 'Players', 'Enemies', 'Inventory', 'Vault', 'World',
  'Tiles', 'Objects', 'Projectiles',
  'Log', 'Settings', 'Timing', 'RealmEngine', 'Position', 'StatusEffect',
  'Panel', 'uiPanel',
  'TreeScript', 'Root', 'Branch', 'Leaf',
  'leaf', 'branch', 'when', 'not', 'always', 'cooldown', 'once', 'sequence', 'parallel',
];

const FALLBACK_MODULES = [
  './RealmEngine.js',
  './types/world/Position.js',
  './types/entities/StatusEffect.js',
  './chat.js',
  './party.js',
  './trade.js',
  './events.js',
  './inventory.js',
  './loot.js',
  './discord.js',
  './guild.js',
  './self/Self.js',
  './walking/Walking.js',
  './combat/Combat.js',
  './players/Players.js',
  './enemies/Enemies.js',
  './inventory/Inventory.js',
  './vault/Vault.js',
  './world/World.js',
  './world/tiles/Tiles.js',
  './world/objects/Objects.js',
  './world/projectiles/Projectiles.js',
  './log/Log.js',
  './settings/Settings.js',
  './timing/Timing.js',
  './ui/Panel.js',
  './treescript/index.js',
];

function makeStub() {
  const sdkExportLines = EXPORT_NAMES
    .map((name) => `  exports.${name} = _sdk.${name};`)
    .join('\n');
  const moduleLines = FALLBACK_MODULES
    .map((mod) => `    Object.assign(fallback, require(${JSON.stringify(mod)}));`)
    .join('\n');
  const fallbackExportLines = EXPORT_NAMES
    .map((name) => `  exports.${name} = fallback.${name};`)
    .join('\n');

  return `'use strict';
// Auto-generated by Realm Engine - do not edit.
// User scripts import this file; calls are forwarded to SDKBridge.

const _sdk = globalThis.__realmengineSDK;
if (_sdk) {
${sdkExportLines}
} else {
  const fallback = {};
${moduleLines}
  fallback.uiPanel = fallback.panel;
${fallbackExportLines}
}
`;
}

function cleanDist() {
  if (!existsSync(SDK_DIST)) {
    console.error('[prepare-sdk] SDK dist not found - run `npm run build:sdk` first.');
    process.exit(1);
  }
  console.log('[prepare-sdk] Keeping all .js files and subdirectories.');
}

function writeStub() {
  writeFileSync(INDEX_SRC, makeStub());
  console.log('[prepare-sdk] Stub written: dist/index.js');
}

function verifyTypes() {
  if (!existsSync(SDK_TYPES)) {
    console.error('[prepare-sdk] dist/types/ not found - SDK types will not be available.');
    return false;
  }
  const indexDts = join(SDK_TYPES, 'index.d.ts');
  if (!existsSync(indexDts)) {
    console.error('[prepare-sdk] dist/types/index.d.ts not found - autocomplete may be incomplete.');
    return false;
  }
  console.log('[prepare-sdk] Types verified: dist/types/');
  return true;
}

function logPackage() {
  try {
    const pkg = JSON.parse(readFileSync(SDK_PKG, 'utf8'));
    console.log(`[prepare-sdk] SDK version: ${pkg.version} (from package.json)`);
  } catch {
    console.warn('[prepare-sdk] Could not read SDK package.json');
  }
}

console.log('[prepare-sdk] Preparing SDK package for Documents deployment...');
console.log(`[prepare-sdk] SDK dist: ${SDK_DIST}`);

cleanDist();
writeStub();
const typesOk = verifyTypes();
logPackage();

console.log('[prepare-sdk] Done. Stub deployed to dist/index.js.');
console.log('[prepare-sdk] Files packaged in installer:');
console.log('         - sdk/dist/index.js (stub)');
console.log('         - sdk/dist/*.js (fallback modules)');
if (typesOk) console.log('         - sdk/dist/types/ (autocomplete)');
console.log('         - sdk/package.json (version info)');
