import { createHash } from 'crypto';
import { readFileSync, existsSync, readdirSync, statSync } from 'fs';
import { resolve, join, relative, sep } from 'path';

export interface ExpectedHash {
  /** Path relative to the project root, using forward slashes. */
  path: string;
  sha256: string;
}

export interface IntegrityViolation {
  file: string;
  reason: 'missing' | 'hash_mismatch' | 'unreadable';
  expected?: string;
  actual?: string;
}

export interface FileIntegrityResult {
  valid: boolean;
  violations: IntegrityViolation[];
}

export interface InjectedFileResult {
  clean: boolean;
  /** Files found in monitored dirs that are not in the allowed list. */
  unexpected: string[];
}

/**
 * File integrity verification utilities.
 *
 * ── Production manifest ──────────────────────────────────────────────────────
 *
 * The expected hashes for the production build are NOT stored here; they are
 * generated by the build script *after* obfuscation and stored in a separate
 * `dist/integrity.json` file that is bundled inside the ASAR archive.
 *
 * The signing flow in build-prod.mjs is:
 *
 *   1.  Bundle + obfuscate  →  dist/app.cjs
 *   2.  FileIntegrity.generateManifest(root, [...paths])  →  hash list
 *   3.  Write hash list to dist/integrity.json
 *   4.  electron-builder packages everything including dist/integrity.json
 *       inside the ASAR
 *
 * At runtime, AntiTamper calls FileIntegrity.loadProductionManifest() which
 * reads dist/integrity.json and passes it to FileIntegrity.verify().
 *
 * ── Dev mode ─────────────────────────────────────────────────────────────────
 *
 * When REALM_ENGINE_PROD is not set the manifest file will not exist and
 * AntiTamper will skip file integrity checks entirely.
 */
export class FileIntegrity {

  // ─── Core utilities ───────────────────────────────────────────────────────

  /**
   * Compute the SHA-256 hex digest of a file.
   * Returns `null` if the file cannot be read.
   */
  static hashFile(filePath: string): string | null {
    try {
      const data = readFileSync(filePath);
      return createHash('sha256').update(data).digest('hex').toLowerCase();
    } catch {
      return null;
    }
  }

  /**
   * Verify a list of files against their expected SHA-256 hashes.
   *
   * @param root    Absolute project root used to resolve relative paths.
   * @param manifest  Array of `{ path, sha256 }` entries.
   */
  static verify(root: string, manifest: ExpectedHash[]): FileIntegrityResult {
    const violations: IntegrityViolation[] = [];

    for (const entry of manifest) {
      const fullPath = resolve(root, entry.path.replace(/\//g, sep));

      if (!existsSync(fullPath)) {
        violations.push({ file: entry.path, reason: 'missing' });
        continue;
      }

      const actual = FileIntegrity.hashFile(fullPath);
      if (actual === null) {
        violations.push({ file: entry.path, reason: 'unreadable' });
        continue;
      }

      const expected = entry.sha256.toLowerCase();
      if (actual !== expected) {
        violations.push({ file: entry.path, reason: 'hash_mismatch', expected, actual });
      }
    }

    return { valid: violations.length === 0, violations };
  }

  // ─── Manifest generation (called from build script) ───────────────────────

  /**
   * Compute SHA-256 hashes for a list of files and return the manifest.
   * Used by build-prod.mjs after obfuscation to create dist/integrity.json.
   *
   * @param root   Absolute project root.
   * @param paths  Paths relative to root (forward slashes).
   */
  static generateManifest(root: string, paths: string[]): ExpectedHash[] {
    return paths.map(p => {
      const fullPath = resolve(root, p.replace(/\//g, sep));
      const sha256 = FileIntegrity.hashFile(fullPath);
      if (!sha256) {
        throw new Error(`FileIntegrity.generateManifest: cannot hash ${fullPath}`);
      }
      return { path: p, sha256 };
    });
  }

  // ─── Production manifest loading ─────────────────────────────────────────

  /**
   * Load the integrity manifest that was written by the build script.
   * Returns an empty array (= skip checks) if the file does not exist,
   * which is the normal case in dev mode.
   *
   * @param root  Absolute project root.
   */
  static loadProductionManifest(root: string): ExpectedHash[] {
    const manifestPath = join(root, 'dist', 'integrity.json');
    if (!existsSync(manifestPath)) return [];

    try {
      const raw = readFileSync(manifestPath, 'utf-8');
      const parsed = JSON.parse(raw) as unknown;
      if (!Array.isArray(parsed)) throw new Error('manifest is not an array');
      return (parsed as ExpectedHash[]).filter(
        e => typeof e.path === 'string' && typeof e.sha256 === 'string'
      );
    } catch (err) {
      // Corrupt or unreadable manifest — treat as a violation at the caller level.
      throw new Error(`FileIntegrity: failed to load manifest: ${(err as Error).message}`);
    }
  }

  // ─── Injected-file scan ───────────────────────────────────────────────────

  /**
   * Scan `electron/` and `dist/` for files that are not in the allowed list.
   * An extra `.js` file silently dropped into `electron/` could be a
   * stealthy require-hook or patch.
   *
   * @param root            Absolute project root.
   * @param allowedRelPaths Set of allowed file paths relative to root
   *                        (forward slashes, e.g. "electron/main.cjs").
   */
  static scanForInjectedFiles(
    root: string,
    allowedRelPaths: ReadonlySet<string>,
  ): InjectedFileResult {
    const unexpected: string[] = [];
    const MONITORED_DIRS = ['electron', 'dist'];

    for (const dir of MONITORED_DIRS) {
      const abs = join(root, dir);
      if (!existsSync(abs)) continue;

      try {
        FileIntegrity.walkDir(abs, (filePath) => {
          const relPath = relative(root, filePath).replace(/\\/g, '/');
          if (!allowedRelPaths.has(relPath)) {
            unexpected.push(relPath);
          }
        });
      } catch {
        // Unreadable directory — not critical for this check.
      }
    }

    return { clean: unexpected.length === 0, unexpected };
  }

  /** Recursively walk a directory, calling `fn` for each file. */
  private static walkDir(dir: string, fn: (filePath: string) => void): void {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const fullPath = join(dir, entry.name);
      if (entry.isDirectory()) {
        FileIntegrity.walkDir(fullPath, fn);
      } else if (entry.isFile()) {
        fn(fullPath);
      }
    }
  }

  // ─── Allowed file lists ───────────────────────────────────────────────────

  /**
   * The canonical set of files that should exist in `electron/` and `dist/`
   * for a production build.  Any file outside this set is suspicious.
   *
   * Update this list whenever a legitimate new file is added to those dirs.
   */
  static readonly PRODUCTION_ALLOWED_FILES: ReadonlySet<string> = new Set([
    'electron/main.cjs',
    'electron/preload.cjs',
    'electron/security.cjs',
    'electron/loading.html',
    'dist/app.cjs',
    'dist/integrity.json',
    // dist/plugins/ entries are dynamic — they are whitelisted by pattern
    // in AntiTamper rather than enumerated here.
  ]);
}
