#include "pch-il2cpp.h"
#include "Handshake.h"
#include "xorstr.h"

// BuildSecrets.h is generated by build-prod.mjs with the shared HMAC key.
// In dev builds where it doesn't exist, create a stub with a dev-only key.
#if __has_include("BuildSecrets.h")
#include "BuildSecrets.h"
#if !defined(_DEBUG)
static_assert(sizeof(BUILD_HANDSHAKE_KEY) > 1, "BUILD_HANDSHAKE_KEY must be defined in release builds");
#endif
#else
#if !defined(_DEBUG)
#error "BuildSecrets.h is required for release builds."
#endif
// Dev fallback must match Client/src/bridge/InternalBridge.ts.
#define BUILD_HANDSHAKE_KEY "47eb249907eb980c851fe3a7bdb56a244244bb7d465572b556e810df6827ecfb"
#endif

#include <bcrypt.h>
#include <iostream>
#pragma comment(lib, "bcrypt.lib")

#ifdef _DEBUG
#define DebugLog(fmt, ...) do { \
    char _dbgBuf[512]; \
    snprintf(_dbgBuf, sizeof(_dbgBuf), fmt, ##__VA_ARGS__); \
    std::cout << "[Handshake] " << _dbgBuf << std::endl; \
} while(0)
#else
#define DebugLog(fmt, ...) (void)0
#endif

namespace Handshake {

// ���─ Hex helpers ─────────────────────────────────────────────────────────────

static uint8_t HexVal(char c) {
    if (c >= '0' && c <= '9') return (uint8_t)(c - '0');
    if (c >= 'a' && c <= 'f') return (uint8_t)(c - 'a' + 10);
    if (c >= 'A' && c <= 'F') return (uint8_t)(c - 'A' + 10);
    return 0;
}

bool IsHexString(const char* s, size_t len) {
    if (!s) return false;
    for (size_t i = 0; i < len; ++i) {
        const char c = s[i];
        const bool isHex =
            (c >= '0' && c <= '9') ||
            (c >= 'a' && c <= 'f') ||
            (c >= 'A' && c <= 'F');
        if (!isHex) return false;
    }
    return true;
}

void ToHex(const uint8_t* data, size_t len, char* out) {
    static const char hex[] = "0123456789abcdef";
    for (size_t i = 0; i < len; ++i) {
        out[i * 2]     = hex[(data[i] >> 4) & 0xF];
        out[i * 2 + 1] = hex[data[i] & 0xF];
    }
    out[len * 2] = '\0';
}

int FromHex(const char* hex, size_t hexLen, uint8_t* out, size_t outCap) {
    size_t byteCount = hexLen / 2;
    if (byteCount > outCap) byteCount = outCap;
    for (size_t i = 0; i < byteCount; ++i)
        out[i] = (HexVal(hex[i * 2]) << 4) | HexVal(hex[i * 2 + 1]);
    return (int)byteCount;
}

// ── Shared key ──────────────────────────────────────────────────────────────

static uint8_t s_keyBytes[32] = {};
static bool    s_keyDecoded = false;
static bool    s_keyStrong = false;

const uint8_t* GetSharedKey() {
    if (!s_keyDecoded) {
        const char* hexKey = BUILD_HANDSHAKE_KEY;
        if (hexKey && strlen(hexKey) == 64 && IsHexString(hexKey, 64)) {
            FromHex(hexKey, 64, s_keyBytes, 32);
            bool allZero = true;
            for (int i = 0; i < 32; ++i) {
                if (s_keyBytes[i] != 0) {
                    allZero = false;
                    break;
                }
            }
            s_keyStrong = !allZero;
        } else {
            memset(s_keyBytes, 0, sizeof(s_keyBytes));
            s_keyStrong = false;
        }
        s_keyDecoded = true;
    }
    return s_keyBytes;
}

bool IsSharedKeyStrong() {
    GetSharedKey();
    return s_keyStrong;
}

void ClearSharedKeyCache() {
    SecureZeroMemory(s_keyBytes, sizeof(s_keyBytes));
    s_keyDecoded = false;
    s_keyStrong = false;
}

// ── Crypto (Windows CNG) ───────────────────────────────────────────────────

bool HmacSha256(const uint8_t* key, size_t keyLen,
                const uint8_t* data, size_t dataLen,
                uint8_t out[32])
{
    BCRYPT_ALG_HANDLE hAlg = NULL;
    BCRYPT_HASH_HANDLE hHash = NULL;
    bool ok = false;

    NTSTATUS st = BCryptOpenAlgorithmProvider(
        &hAlg, BCRYPT_SHA256_ALGORITHM, NULL, BCRYPT_ALG_HANDLE_HMAC_FLAG);
    if (!BCRYPT_SUCCESS(st)) goto done;

    st = BCryptCreateHash(hAlg, &hHash, NULL, 0,
                          (PUCHAR)key, (ULONG)keyLen, 0);
    if (!BCRYPT_SUCCESS(st)) goto done;

    st = BCryptHashData(hHash, (PUCHAR)data, (ULONG)dataLen, 0);
    if (!BCRYPT_SUCCESS(st)) goto done;

    st = BCryptFinishHash(hHash, out, 32, 0);
    ok = BCRYPT_SUCCESS(st);

done:
    if (hHash) BCryptDestroyHash(hHash);
    if (hAlg)  BCryptCloseAlgorithmProvider(hAlg, 0);
    return ok;
}

bool GenRandom(uint8_t* buf, size_t len) {
    return BCRYPT_SUCCESS(
        BCryptGenRandom(NULL, buf, (ULONG)len, BCRYPT_USE_SYSTEM_PREFERRED_RNG));
}

// ── Auth state ──────────────────────────────────────────────────────────────

void ResetAuthState(AuthState* state) {
    state->authenticated = false;
    state->userId[0] = '\0';
    state->heartbeatMisses = 0;
    state->lastHeartbeatSent = 0;
    state->lastHeartbeatRecv = 0;
    state->pendingChallenge[0] = '\0';
    state->challengePending = false;
    memset(state->sessionKey, 0, sizeof(state->sessionKey));
    state->sessionReady = false;
    state->lastClientSeq = 0;
    state->nextServerSeq = 1;
}

bool IsHealthy(const AuthState* state) {
    return state->authenticated && state->heartbeatMisses < HEARTBEAT_MAX_MISSES;
}

// ── Challenge / Response ────────────────────────────────────────────────────

bool GenerateChallenge(char hexOut[65]) {
    uint8_t nonce[32];
    if (!GenRandom(nonce, 32)) return false;
    ToHex(nonce, 32, hexOut);
    return true;
}

bool ComputeResponse(const char* data, size_t dataLen, char hexOut[65]) {
    if (!IsSharedKeyStrong()) return false;
    uint8_t mac[32];
    if (!HmacSha256(GetSharedKey(), 32,
                    reinterpret_cast<const uint8_t*>(data), dataLen, mac))
        return false;
    ToHex(mac, 32, hexOut);
    return true;
}

bool VerifyResponse(const char* data, size_t dataLen, const char* hexResp) {
    // Compute expected
    char expected[65];
    if (!ComputeResponse(data, dataLen, expected))
        return false;

    // Constant-time compare (64 hex chars + NUL)
    if (strlen(hexResp) != 64) return false;
    uint8_t diff = 0;
    for (int i = 0; i < 64; ++i)
        diff |= (uint8_t)(expected[i] ^ hexResp[i]);
    return diff == 0;
}

} // namespace Handshake
