/**
 * Condition effect bitmask indices.
 * Effects[0] holds bits 0-30, Effects[1] holds bits 31+.
 */
export const ConditionEffect = {
  Dead: 0,
  Quiet: 1,
  Weak: 2,
  Slowed: 3,
  Sick: 4,
  Dazed: 5,
  Stunned: 6,
  Blind: 7,
  Hallucinating: 8,
  Drunk: 9,
  Confused: 10,
  StunImmune: 11,
  Invisible: 12,
  Paralyzed: 13,
  Speedy: 14,
  Bleeding: 15,
  ArmorBrokenImmune: 16,
  Healing: 17,
  Damaging: 18,
  Berserk: 19,
  Paused: 20,
  Stasis: 21,
  StasisImmune: 22,
  Invincible: 23,
  Invulnerable: 24,
  Armored: 25,
  ArmorBroken: 26,
  Hexed: 27,
  NinjaSpeedy: 28,
  Unstable: 29,
  Darkness: 30,
  // Effects[1] bits (index - 31)
  SlowedImmune: 31,
  DazedImmune: 32,
  ParalyzeImmune: 33,
  Petrified: 34,
  PetrifiedImmune: 35,
  PetDisable: 36,
  Curse: 37,
  CurseImmune: 38,
  HpBoost: 39,
  MpBoost: 40,
  AttBoost: 41,
  DefBoost: 42,
  SpdBoost: 43,
  VitBoost: 44,
  WisBoost: 45,
  DexBoost: 46,
  Silenced: 47,
  Exposed: 48,
  Energized: 49,
  InCombat: 58,
} as const;

export type ConditionEffectName = keyof typeof ConditionEffect;
