export enum StatusEffect {
    CURSED        = 'cursed',
    SLOWED        = 'slowed',
    STUNNED       = 'stunned',
    BLIND         = 'blind',
    HALLUCINATING = 'hallucinating',
    DRUNK         = 'drunk',
    CONFUSED      = 'confused',
    STASIS        = 'stasis',
    INVISIBLE     = 'invisible',
    ARMORED       = 'armored',
    INVINCIBLE    = 'invincible',
    SPEEDY        = 'speedy',
    HEALING       = 'healing',
    DAMAGING      = 'damaging',
    BERSERK       = 'berserk',
    PETRIFIED     = 'petrified',
    SICK          = 'sick',
    BLEEDING      = 'bleeding',
    QUIET         = 'quiet',
    EXPOSED       = 'exposed',
    HEXED         = 'hexed',
}
